version: '3.9'
services:
  kong-db:
    image: postgres:latest
    container_name: kong-db
    hostname: kong-db
    networks:
      - project
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    
  kong-migrations:
    image: kong
    command: kong migrations bootstrap
    container_name: kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    networks:
      - project
    depends_on:
      kong-db:
        condition: service_started
  
  kong:
    image: kong
    container_name: kong
    hostname: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001,0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    networks:
      - project 
    
  konga:
    hostname: konga
    image: pantsel/konga
    ports:
      - "1337:1337"
    container_name: konga
    environment:
      - NODE_ENV=production

    networks:
      - project

  echoserver:
    hostname: echoserver
    image: ealen/echo-server
    networks:
      - project

networks:
  project:
    driver: bridge
